### ISSUE TITLE
Add lint into Check

### ISSUE THREAD

**Issue by qhy040404** [qhy040404/Library-One-Tap-Android#173]
```gradle
id 'org.jlleitschuh.gradle.ktlint' version '10.3.0' apply false
id 'io.gitlab.arturbosch.detekt' version '1.21.0' apply false
```

```yaml
- name: Ktlint
  uses: gradle/gradle-build-action@v2.2.2
  with:
    arguments: ktlintCheck --warning-mode all --scan
- name: Check_debug
  uses: gradle/gradle-build-action@v2.2.2
  with:
    arguments: detekt --warning-mode all --scan
```
